// <auto-generated />
using System;
using AuthRepository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthMigrations.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20200704222852_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuthRepository.DataModels.AuthUser", b =>
                {
                    b.Property<byte[]>("AuthUserGuid")
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(264)")
                        .HasMaxLength(264);

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(264)")
                        .HasMaxLength(264);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("AuthUserGuid");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AuthUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
